### ISSUE TITLE
Product Detail Page Not Working

### ISSUE THREAD

**Issue by Vikram0811** [php-cuong/magento2-product-question-and-answer#2]
After successful installation on Mage ver 2.2.2, I was unable to access product detail page and it was showing 500 error. Moreover, I could not find anything in logs too. Though I was able to access admin and can see Product Question section appearing.

Also in this extension, can admin answer the questions asked by customers ?

Thanks.

**Comment by WeableSupport** [comment]
I can't see the Product Question admin side?

**Comment by php-cuong** [comment]
This is the demo, you should use the pro version of this extension, it has the price is $299, let me know if you are interested in the pro version.

**Comment by php-cuong** [comment]
You can get the professional version at the link https://github.com/php-cuong/magento2-product-question-and-answer-pro
