### ISSUE TITLE
Moderation page in backend for allow/disallow questions?

### ISSUE THREAD

**Issue by muammarmuhammad** [php-cuong/magento2-product-question-and-answer#3]
Hi Where is moderation page in backend for allow/disallow questions?
and how to answer the question from backend?

**Comment by php-cuong** [comment]
This is the demo, you should use the pro version of this extension, it has the price is $299, let me know if you are interested in the pro version.

**Comment by php-cuong** [comment]
You can get the professional version at the link https://github.com/php-cuong/magento2-product-question-and-answer-pro
