### ISSUE TITLE
Question moderation 

### ISSUE THREAD

**Issue by praveen5exceptions** [php-cuong/magento2-product-question-and-answer#4]
Where is product question moderation in admin panel for allow/disallow question/answer ?

**Comment by php-cuong** [comment]
This is the demo, you should use the pro version of this extension, it has the price is $299, let me know if you are interested in the pro version.

**Comment by php-cuong** [comment]
You can get the professional version at the link https://github.com/php-cuong/magento2-product-question-and-answer-pro
