### ISSUE TITLE
On product details page

### ISSUE THREAD

**Issue by vaibhav7290** [php-cuong/magento2-product-question-and-answer#5]
When that module add in my website then js error show at the console & that will stop load of all js in product details page.
![screenshot - saturday 30 june 2018 - 11 34 17 ist](https://user-images.githubusercontent.com/40710543/42122091-00a6462a-7c5a-11e8-87b8-c34de7985c42.png)

**Comment by php-cuong** [comment]
You can get the professional version at the link https://github.com/php-cuong/magento2-product-question-and-answer-pro

**Comment by vaibhav7290** [comment]
okay...thanks
