### ISSUE TITLE
Installation error. PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted

### ISSUE THREAD

**Issue by Tonop** [php-cuong/magento2-product-question-and-answer#6]
Hi Cuong!

I use your FAQ extension and decided to try Q&A. But during installation I got memory error. Why in the hell does this module eat up so much memory? :) 
Or I am doing smth wrong?

-sh-4.1$ composer require php-cuong/magento2-product-question-and-answer
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "/usr/local/bin/composer self-update" to get the latest version.
Using version ^2.2 for php-cuong/magento2-product-question-and-answer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 32 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleWatchNode.php on line 40

Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 32 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleWatchNode.php on line 40

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.-sh-4.1$ composer require

**Comment by php-cuong** [comment]
You should update the composer version you are using now.
